### PR TITLE
upgraded to boostrap 3.3.7 and added server status icons

### PR DESCRIPTION
**Pull request by interdigitize**
Worked on with @jimthoburn

---

Made at [CodeLabOC](https://github.com/codelaboc) 🎃 🍊

### CODE REVIEW

**Comment by interdigitize** [comment]
Hi, just following up. Please let me know if I need to adjust the code. Thanks

**Comment by gr2m** [comment]
@machikoyasuda you got this PR?

**Comment by machikoyasuda** [comment]
This looks good to me. How about you @gr2m???

**Comment by gr2m** [comment]
great work 👏

**Pull request merged**
